require('aj.settings')
require('aj.utils')
require('aj.plugins')
require('aj.glow')
require('aj.lsp')
require('aj.custom')
require('aj.null_ls')
require('aj.keymaps')
require('aj.treesitter')
require('aj.autocmd')
require('aj.greeter')
require('aj.lualine')
require('aj.customShell')
require('aj.flutter-setup')
require('aj.legend')
require('aj.luasnip')
-- require('aj.express-line')
-- require('aj.lsp-saga')

require('aj.fzf_utils.git-version')
