require('aj.settings')
require('aj.utils')
require('aj.plugins')
require('aj.lsp')
require('aj.custom')
require('aj.null_ls')
require('aj.keymaps')
require('aj.treesitter')
require('aj.autocmd')
require('aj.greeter')
-- require('aj.lsp-saga')

require('aj.fzf_utils.git-version')
